version: "3.8"

services:
  radarr:
    image: linuxserver/radarr:6.1.1
    pull_policy: if_not_present
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/docker/radarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies:/movies
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "2"
          memory: 4G
