version: "3.8"

services:
  sabnzbd:
    image: linuxserver/sabnzbd:4.5.5
    pull_policy: if_not_present
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/docker/sabnzbd:/config
      - /mnt/downloads:/downloads
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "4"
          memory: 4G
