version: "3.8"

services:
  transmission:
    image: linuxserver/transmission:4.1.1
    pull_policy: if_not_present
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/docker/transmission:/config
      - /mnt/downloads:/downloads
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "1"
          memory: 1G
